apiVersion: v1
kind: Pod
metadata:
  name : redis-v2
  labels:
    run: manual
    env: production
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP