apiVersion: v1
kind: Pod
metadata:
  name : layer-7-load-balancer
spec:
  containers:
  - image: aminur932/loadbalancer
    name: loadbalancer
    ports:
    - containerPort: 80
      protocol: TCP

  - image: redis
    name: redis
    ports:
    - containerPort: 6379
      protocol: TCP
      
  - image: aminur932/microservice1
    name: microservice1
    ports:
    - containerPort: 7001
      protocol: TCP
      
  - image: aminur932/microservice2
    name: microservice2
    ports:
    - containerPort: 7002
      protocol: TCP
      
  - image: aminur932/microservice3
    name: microservice3
    ports:
    - containerPort: 7003
      protocol: TCP
      