apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodejs-ds
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
        disk: ssd
      containers:
      - name: main
        image: aminur932/simple-nodejs